### ISSUE TITLE
Early map to dos

### ISSUE THREAD

**Issue by DanielJWood** [nprapps/ice-melt#79]
Art Direction questions:
- [x] What level of simplification to make it?
- [x] How to add/where color?
- [x] #84
- [x] How to approach adding real data (gulf of Maine water, whales, etc)
- [ ] What should ice look like in this system? #80 
- [ ] What amount of labels (oceans, land, etc) to have?
- [x] How to approach Nepal/inland maps? 
- [x] How do locator maps look? Still sketchy?

Technical:
- [x] How to draw the arrows? Should the arrow lines be drawn into QGIS in the coordinate system? or somehow else?
- [ ] How to draw labels? #81 
- [x] Make available the pitch/roll/yaw/zoom levels from any drag point.
- [x] Create zoom/pan transitions
- [x] Bring all over from observable to interactive rig #82
- [ ] Can we fade from a satellite image to the sketchy map?
- [ ] Ability to change to different (higher) fidelity land data at certain scenes #83 

Lower Priority:
- [x] Swirling eddies data possible to approximate??
